routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Http\Controllers\CategoriesController;
use App\Http\Controllers\FrontEndChurchController;
use App\Http\Controllers\FrontEndController;
use App\Http\Controllers\RepresentativesController;


Route::get('/', 'FrontEndController@home')->name('home');

Route::get('/admin', 'SessionsController@index')->name('admin')->middleware('auth');

//Δημιουργία/Είσοδος Διαχειριστών
Route::get('admin/admins', 'RegistrationController@index');
Route::get('admin/register', 'RegistrationController@create')->middleware('auth');
Route::post('admin/register', 'RegistrationController@store');
Route::get('admin/{user}/edit', 'RegistrationController@edit')->name('admin.edit');
Route::put('admin/{user}', 'RegistrationController@update')->name('admin.update');
Route::get('/admin/login', 'SessionsController@create')->name('admin.login')->middleware('guest');
Route::post('/admin/login', 'SessionsController@store');
Route::get('/admin/logout', 'SessionsController@destroy');

//Admin Panel
Route::group(['middleware' => 'auth', 'prefix' => 'admin', 'as' => 'admin.'], function() {

    //Κατηγορίες
    Route::post('/categoryorder', 'CategoriesController@order');
    Route::resource('/categories', 'CategoriesController')->name('*','categories');

    // //Σελίδες SEO
    Route::post('pageorder', 'AdminPagesController@order');
    Route::resource('pages', 'AdminPagesController')->name('*', 'pages');

    //Πληροφοριακές Σελίδες 
    Route::post('/infopagesorder', 'InfoPagesController@order');
    Route::resource('/infopages', 'InfoPagesController')->name('*', 'infopages');

    //Περιφέρειες
    Route::resource('/districts', 'DistrictsController')->name('*', 'districts');

    //Πελάτες
    Route::post('/clients/search', 'ClientsController@search');
    Route::resource('/clients', 'ClientsController')->name('*', 'clients');

    //Πωλητές
    Route::resource('/representatives', 'RepresentativesController')->name('*', 'representatives');

    //Καταχωρήσεις
    Route::post('/entries/search', 'EntriesController@search');
    Route::resource('/entries', 'EntriesController')->name('*', 'entries');

    //Διαχείριση Φωτογραφιών
    Route::get('/entries/albums/{id}', 'AlbumsController@index');
    Route::get('/entries/albums/{id}/create', 'AlbumsController@create');
    Route::post('/entries/albums', 'AlbumsController@store');
    Route::put('/entries/albums/{entryid}/{albumid}/updatedescription', 'AlbumsController@update');
    Route::post('/entries/albums/{entryid}/{albumid}/updatecover', 'AlbumsController@updateCover');
    Route::put('/entries/albums/{entryid}/{albumid}/updatetitle', 'AlbumsController@updateTitle');
    Route::get('/entries/albums/{entryid}/{albumid}/edit', 'AlbumsController@edit');
    Route::post('/entries/albums/albumorder', 'AlbumsController@order');
    Route::get('/entries/albums/{albumid}/delete', 'AlbumsController@destroy');
    Route::post('/entries/albums/{entryid}/{albumid}/', 'ImagesController@store');
    Route::post('/entries/albums/{entryid}/{albumid}/imageorder', 'ImagesController@order');
    Route::get('/entries/albums/{entryid}/{albumid}/{imageid}/delete', 'ImagesController@destroy');
    Route::post('/entries/albums/{entryid}/{albumid}/{imageid}', 'ImagesController@storeDescription');
    Route::post('/entries/albums/{entryid}/{albumid}/{imageid}/edit', 'ImagesController@changeAlbum');

    //Διαχείριση video
    Route::get('/entries/video/{id}', 'VideoController@index');
    Route::post('/entries/video/videoorder', 'VideoController@order');
    Route::post('/entries/video/{id}', 'VideoController@store');
    Route::get('/entries/video/{id}/{videoid}/delete', 'VideoController@destroy');

    //Facilities: Εκκλησίες - Δημαρχεία
    Route::post('/churches/search', 'AdminChurchController@search');
    Route::resource('/churches', 'AdminChurchController')->name('*', 'churches');

    // Μητροπόλεις
    Route::resource('/metropoles', 'AdminMetropolesController')->name('*', 'metropoles');

    // Δημαρχεία
    Route::post('/municipalities/search', 'MunicipalityController@search');
    Route::resource('/municipalities', 'MunicipalityController')->name('*', 'municipalities');


    // Tags
    Route::resource('/tags', 'AdminTagsController')->name('*', 'tags');

    // Tag Pages
    Route::post('/tagpagesorder', 'AdminTagPagesController@order');
    Route::resource('/tagpages', 'AdminTagPagesController')->name('*', 'tagpages');
    

    //Banners
    Route::post('/banners/entry', 'BannersController@cliententry');
    Route::resource('/banners', 'BannersController')->name('*','banners');

    //Sliders
    Route::post('/sliders/sliderentry', 'SlidersController@sliderentry');
    Route::resource('/sliders', 'SlidersController')->name('*', 'sliders');

    //News
    Route::post('/news/newsorder', 'NewsController@order');
    Route::resource('/news', 'NewsController')->name('*', 'news');

    // Testimonials
    Route::post('/testimonials/testimonialsorder', 'TestimonialsController@order');
    Route::resource('/testimonials', 'TestimonialsController')->name('*', 'testimonials');

});

//Clientarea
Route::prefix('clientarea')->group(function(){
    Route::get('/login', 'Auth\ClientLoginController@showLoginForm')->name('clientarea.login');
    Route::post('/login', 'Auth\ClientLoginController@login');
    Route::get('/logout', 'Auth\ClientLoginController@destroy');
    Route::get('/', 'ClientAreaController@index');
    Route::get('/', 'ClientAreaController@show');
    Route::get('/{entryid}/info', 'ClientAreaController@info');
    Route::put('/{entryid}/info', 'ClientAreaController@updateInfo');
    //Password reset
    Route::post('/password/email', 'Auth\ClientForgotPasswordController@sendResetLinkEmail')->name('client.password.email');
    Route::get('/password/reset', 'Auth\ClientForgotPasswordController@showLinkRequestForm')->name('client.password.request');
    Route::post('/password/reset', 'Auth\ClientResetPasswordController@reset');
    Route::get('/password/reset/{token}', 'Auth\ClientResetPasswordController@showResetForm')->name('client.password.reset');
    //Albums
    Route::get('/{entryid}/albums', 'ClientAreaController@albums');
    Route::get('/{entryid}/albums/create', 'ClientAreaController@albumsCreate');
    Route::post('/{entryid}/albums', 'ClientAreaController@albumsStore');
    Route::get('/{entryid}/albums/{albumid}/edit', 'ClientAreaController@albumsEdit');
    // Route::put('/{clientid}/{entryid}/albums/{albumid}', 'ClientAreaController@albumsUpdate');
    Route::put('/{entryid}/albums/{albumid}/updatetitle', 'ClientAreaController@albumsUpdateTitle');
    Route::put('/{entryid}/albums/{albumid}/updatedescription', 'ClientAreaController@albumsUpdateDescription');
    Route::post('/{entryid}/albums/{albumid}/updatecover', 'ClientAreaController@albumsUpdateCover');
    Route::post('/{entryid}/albums/albumorder', 'ClientAreaController@albumsOrder');
    Route::get('/{entryid}/albums/{albumid}/delete', 'ClientAreaController@albumsDestroy');
    //Images
    Route::post('/{entryid}/{albumid}', 'ClientAreaController@imagesStore');
    Route::post('/{entryid}/albums/{albumid}/imageorder', 'ClientAreaController@imagesOrder');
    Route::get('/{albumid}/{imageid}/delete', 'ClientAreaController@imageDestroy');
    Route::post('{entryid}/albums/{albumid}/{imageid}', 'ClientAreaController@imageStoreDescription');
    Route::post('/{entryid}/albums/{albumid}/{imageid}/edit', 'ClientAreaController@changeAlbum');
    //Διαχείριση video
    Route::get('/{entryid}/video', 'ClientAreaController@videoIndex');
    Route::post('/{entryid}/video/videoorder', 'ClientAreaController@videoOrder');
    Route::post('/{entryid}/video/addvideo', 'ClientAreaController@videoStore');
    Route::get('/{entryid}/video/{videoid}/delete', 'ClientAreaController@videoDestroy');
});


//FrontEnd
// Route::get('/lucky', 'FrontEndController@feelingLucky');
Route::get('/sitemap.xml', 'SitemapController@index');

Route::get('/ekklisies.php', 'FrontEndChurchController@churchesPage');
Route::post('/ekklisies.php', 'FrontEndController@searchChurchesPage');
Route::get('/dimarxeia.php', 'FrontEndController@municipalitiesPage');
Route::post('/dimarxeia.php', 'FrontEndController@searchMunicipalitiesPage');
Route::get('/bridal-expo.php', 'FrontEndController@bridalexpo');
Route::get('testimonials.php', 'FrontEndTestimonialsController@show');
Route::post('/emailsent', 'FrontEndController@emailsent');
Route::post('/phonecall', 'FrontEndController@phonecall');
Route::get('/rotation', 'RotationExpirationController@entriesRotation');
Route::get('/expirations', 'RotationExpirationController@entriesExpiration');
// Route::get('/changedates', 'RotationExpirationController@changeDates');
Route::get('/slidersexpirations', 'RotationExpirationController@slidersExpiration');
Route::get('/tags/{slug}', 'TagPagesController@show');
Route::get('/thanks', 'FrontEndController@thanks');
Route::get('/{slug}', 'FrontEndController@pages')->name('page');
Route::post('/{slug}', 'FrontEndController@infoPageContact');
Route::get('/{district}', 'FrontEndController@district')->name('district');
Route::get('/{district}/dimarxeia', 'FrontEndController@municipalities');
Route::post('/{district}/dimarxeia', 'FrontEndController@searchMunicipality');
Route::get('/{district}/dimarxeia/{municipality}', 'FrontEndController@municipalityEntry');

Route::get('/{district}/ekklisies', 'FrontEndMetropoleController@index');
Route::post('/{district}/ekklisies', 'FrontEndMetropoleController@select');
Route::get('/{district}/ekklisies/{metropole}', 'FrontEndMetropoleController@show');

app/District.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class District extends Model
{
    protected $guarded = [];

    private $rules = [
            'name' => 'required|min:5',
            'slug' => 'required|min:5',
            'metatitle' => 'required|min:5',
            'metadescription' => 'required|min:5',
            'metakeywords' => 'required|min:5',
        ];

    public function validation($request)
    {
        return $request->validate($this->rules);
    }

    public function banners(){
        return $this->belongsToMany(Banner::class);
    }

    public function entries(){
        return $this->hasMany(Entry::class, 'dist_id');
    }

    public function churches(){
        return $this->hasMany(Church::class);
    }

    public function links(){
        return $this->belongsToMany(Link::class);
    }

    public function municipalities(){
        return $this->hasMany(Municipality::class);
    }

    public function metropoles() {
        return $this->hasMany(Metropole::class);
    }
    
}

app/Http/Controllers/DistrictsController.php
<?php

namespace App\Http\Controllers;

use App\District;
use Illuminate\Http\Request;

class DistrictsController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $districts = District::all();
        return view('admin.districts.index', compact('districts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.districts.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        
        $district = new District();

        $attributes = $district->validation($request);

        $district->create($attributes);

        $district = District::all()->last();

        
        //Redirect
        if($request->submitbutton == 'save'){
            return redirect()->route('admin.districts.edit', $district); 
        } elseif ($request->submitbutton == 'save-close') {
            return redirect()->route('admin.districts.index');
        } elseif ($request->submitbutton == 'save-new'){
            return redirect(route('admin.districts.create'));
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\District  $district
     * @return \Illuminate\Http\Response
     */
    public function show(District $district)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\District  $district
     * @return \Illuminate\Http\Response
     */
    public function edit(District $district)
    {
    
        return view('admin.districts.edit', compact('district'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\District  $district
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, District $district)
    {
        $attributes = $district->validation($request);

        $district->update($attributes);

        // $districts->name = $request->input('name');
        // $districts->slug = $request->input('slug');
        // $districts->metatitle = $request->input('metatitle');
        // $districts->metadescription = $request->input('metadescription');
        // $districts->metakeywords = $request->input('metakeywords');
        // $districts->save();

        //Redirect
        if($request->submitbutton == 'save'){
            return redirect()->route('admin.districts.edit', $district); 
        } elseif ($request->submitbutton == 'save-close') {
            return redirect()->route('admin.districts.index');
        } elseif ($request->submitbutton == 'save-new'){
            return redirect()->route('admin.districts.create');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\District  $district
     * @return \Illuminate\Http\Response
     */
    public function destroy(District $district)
    {
        $district->delete();

        return redirect()->route('admin.districts.index');
    }
}

resources/views/admin/districts/create.blade.php
@extends('admin.layouts.master')

@section('content')

<h1>Δημιουργία Περιφέρειας</h1>

<div class="">

<form method="post" action="{{route('districts.store')}}">
    @csrf

    <div class="form-group">
        <label for="name">Όνομα Περιφέρειας</label>
        <input id="name" class="form-control" type="text" name="name" value="{{old('name')}}">
        @error('name')
            <span class="text-danger">{{$message}}</span>
        @enderror
    </div>
    
    <div class="form-group">
        <label for="slug">slug</label>
        <input id="slug" class="form-control" type="text" name="slug" value="{{old('slug')}}">
        @error('slug')
            <span class="text-danger">{{$message}}</span>
        @enderror
    </div>
    <div class="form-group">
        <label for="metatitle">Meta Title Περιφέρειας</label>
        <input id="metatitle" class="form-control" type="text" name="metatitle" value="{{old('metatitle')}}">
        @error('metatitle')
            <span class="text-danger">{{$message}}</span>
        @enderror
    </div>
    <div class="form-group">
        <label for="metadescription">Meta Description Περιφέρειας</label>
        <input id="metadescription" class="form-control" type="text" name="metadescription" value="{{old('metadescription')}}">
        @error('metadescription')
            <span class="text-danger">{{$message}}</span>
        @enderror
    </div>
    <div class="form-group">
        <label for="metakeywords">Meta Keywords Περιφέρειας</label>
        <input id="metakeywords" class="form-control" type="text" name="metakeywords" value="{{old('metakeywords')}}">
        @error('metakeywords')
            <span class="text-danger">{{$message}}</span>
        @enderror
    </div>

    <div class="d-flex justify-content-around">
        <button class="btn btn-primary" type="submit" name="submitbutton" value="save-close">Save & Close</button>
        <button class="btn btn-success" type="submit" name="submitbutton" value="save">Save</button>
        <button class="btn btn-btn-secondary" type="submit" name="submitbutton" value="save-new">Save & New</button>
        <a class="btn btn-warning" href="{{route('districts.index')}}">Cancel</a>
    </div>
    
</form>

</div>


@endsection

resources/views/admin/districts/edit.blade.php
@extends('admin.layouts.master')

@section('content')
<h1>Επεξεργασία Περιφέρειας: {{$district->name}} </h1>

<form method="post" action="{{route('admin.districts.update', $district)}}">
    @csrf
    @method('PUT')

    <div class="form-group">
        <label for="name">Όνομα Περιφέρειας</label>
        <input id="name" class="form-control" type="text" name="name" value="{{$district->name}}">
        @error('name')
            <span class="text-danger">{{$message}}</span>
        @enderror
    </div>
    
    <div class="form-group">
        <label for="slug">slug</label>
        <input id="slug" class="form-control" type="text" name="slug" value="{{$district->slug}}">
        @error('slug')
            <span class="text-danger">{{$message}}</span>
        @enderror
    </div>
    <div class="form-group">
        <label for="metatitle">Meta Title Περιφέρειας</label>
        <input id="metatitle" class="form-control" type="text" name="metatitle" value="{{$district->metatitle}}">
        @error('metatitle')
            <span class="text-danger">{{$message}}</span>
        @enderror
    </div>
    <div class="form-group">
        <label for="metadescription">Meta Description Περιφέρειας</label>
        <input id="metadescription" class="form-control" type="text" name="metadescription" value="{{$district->metadescription}}">
        @error('metadescription')
            <span class="text-danger">{{$message}}</span>
        @enderror
    </div>
    <div class="form-group">
        <label for="metakeywords">Meta Keywords Περιφέρειας</label>
        <input id="metakeywords" class="form-control" type="text" name="metakeywords" value="{{$district->metakeywords}}">
        @error('metakeywords')
            <span class="text-danger">{{$message}}</span>
        @enderror
    </div>

    <div class="d-flex justify-content-around">
        <button class="btn btn-primary" type="submit" name="submitbutton" value="save-close">Save & Close</button>
        <button class="btn btn-success" type="submit" name="submitbutton" value="save">Save</button>
        <button class="btn btn-btn-secondary" type="submit" name="submitbutton" value="save-new">Save & New</button>
        <a class="btn btn-warning" href="{{route('admin.districts.index')}}">Cancel</a>
    
    
</form>
        <form action="{{route('admin.districts.destroy', $district)}}" method="post">
            @csrf
            @method('DELETE')
            <button class="btn btn-danger" type="submit">DELETE</button>
        </form>
    </div>

</div>


@endsection

resources/views/admin/districts/index.blade.php
@extends ('admin.layouts.master')

@section('content')

<h1>Περιφέρειες</h1>

<ul class="list-group">
    @foreach ($districts as $district)

        <li class="list-group-item"><a href="districts/{{$district->id}}/edit"><span> {{$district->id}} </span> - {{$district->name}}</a></li>
        
    @endforeach
</ul>
<div class="col-md-12">
    <a href="districts/create" class="btn btn-primary">Προσθήκη Περιφέρειας</a>
</div>


@endsection